[package]
name = "scarlett-solo-fix"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.3"
anyhow = "1.0"
ringbuf = "0.4.1"
clap = { version = "4.0", features = ["derive"] }
ctrlc = "3.4.5"